# Generated by Django 4.1.3 on 2022-11-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondhand_book", "0002_goods_commodity_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="Img",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
