# Generated by Django 4.1.3 on 2022-11-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondhand_book", "0003_goods_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="Img",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
