# Generated by Django 4.1.3 on 2022-11-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondhand_book", "0004_userinfo_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="verification_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
